# Generated by Django 4.1.9 on 2023-05-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
