# Generated by Django 4.1.9 on 2023-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='aut_1',
            field=models.CharField(default='', max_length=100, verbose_name='AUT 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='aut_2',
            field=models.CharField(default='', max_length=100, verbose_name='AUT 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='aut_3',
            field=models.CharField(default='', max_length=100, verbose_name='AUT 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='aut_4',
            field=models.CharField(default='', max_length=100, verbose_name='AUT 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='aut_5',
            field=models.CharField(default='', max_length=100, verbose_name='AUT 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='liquido_1',
            field=models.CharField(default='', max_length=100, verbose_name='LIQUIDO 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='liquido_2',
            field=models.CharField(default='', max_length=100, verbose_name='LIQUIDO 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='liquido_3',
            field=models.CharField(default='', max_length=100, verbose_name='LIQUIDO 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='liquido_4',
            field=models.CharField(default='', max_length=100, verbose_name='LIQUIDO 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='liquido_5',
            field=models.CharField(default='', max_length=100, verbose_name='LIQUIDO 5'),
            preserve_default=False,
        ),
    ]
