# Generated by Django 4.1.9 on 2023-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario_aut_1_funcionario_aut_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_fc',
            field=models.IntegerField(verbose_name='CODIGO FC'),
        ),
    ]
