# Generated by Django 4.1.9 on 2023-05-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_cargo_alter_funcionario_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='competencia',
            field=models.CharField(max_length=100, verbose_name='Competencia'),
        ),
    ]
