# Generated by Django 4.1.9 on 2023-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_competencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['comp', 'matricula']},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='competencia',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='comp',
            field=models.IntegerField(default=1, verbose_name='Comp'),
            preserve_default=False,
        ),
    ]
